# Generated by Django 5.0 on 2023-12-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'verbose_name': 'Any Query', 'verbose_name_plural': 'Any Queries'},
        ),
    ]
