# Generated by Django 5.0 on 2023-12-11 20:26

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_query_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('date', models.TimeField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('facebook', models.URLField(verbose_name='Facebook URL')),
                ('twitter', models.URLField(verbose_name='Twitter URL')),
                ('linkedin', models.URLField(verbose_name='Linkedin URL')),
                ('instagram', models.URLField(verbose_name='Instagram URL')),
            ],
            options={
                'verbose_name': 'Header Info',
                'verbose_name_plural': 'Headers Infos',
            },
        ),
    ]
