# Generated by Django 5.0 on 2023-12-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSliderL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('doctors', models.SmallIntegerField(max_length=20, verbose_name='Expert Doctors')),
                ('stuff', models.SmallIntegerField(max_length=20, verbose_name='Medical Stuff')),
                ('patients', models.SmallIntegerField(max_length=20, verbose_name='Total Patients')),
            ],
            options={
                'verbose_name': 'General Slider  Left',
                'verbose_name_plural': 'General Slider  Left',
            },
        ),
        migrations.CreateModel(
            name='GeneralSliderR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('img', models.ImageField(upload_to='media', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'General Slider Right',
                'verbose_name_plural': 'General Sliders Right',
            },
        ),
    ]
