# Generated by Django 5.0 on 2023-12-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_generalsliderl_generalsliderr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='date',
            new_name='date2',
        ),
        migrations.AddField(
            model_name='header',
            name='date1',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='header',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='header',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='Linkedin URL'),
        ),
        migrations.AlterField(
            model_name='header',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='Twitter URL'),
        ),
    ]
