# Generated by Django 5.0 on 2023-12-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_date_header_date2_header_date1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='day_of_week',
            field=models.IntegerField(null=True),
        ),
    ]
