# Generated by Django 5.0 on 2023-12-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_header_day_last_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='header',
            name='date2',
        ),
        migrations.RemoveField(
            model_name='header',
            name='phone',
        ),
        migrations.AddField(
            model_name='header',
            name='text',
            field=models.CharField(max_length=50, null=True, verbose_name='Time'),
        ),
    ]
