# Generated by Django 5.0 on 2023-12-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_header_date1_remove_header_date2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('text1', models.TextField(max_length=255, verbose_name='First Text')),
                ('text2', models.TextField(max_length=255, verbose_name='Second Text')),
                ('note1', models.CharField(max_length=20, verbose_name='First Note')),
                ('note2', models.CharField(max_length=20, verbose_name='Second Note')),
                ('note3', models.CharField(max_length=20, verbose_name='Third Note')),
                ('img1', models.ImageField(upload_to='media', verbose_name='First Image')),
                ('img2', models.ImageField(upload_to='media', verbose_name='Second Image')),
            ],
            options={
                'verbose_name': 'About Us ',
                'verbose_name_plural': 'About Uses',
            },
        ),
        migrations.AlterField(
            model_name='generalsliderl',
            name='doctors',
            field=models.SmallIntegerField(verbose_name='Expert Doctors'),
        ),
        migrations.AlterField(
            model_name='generalsliderl',
            name='patients',
            field=models.SmallIntegerField(verbose_name='Total Patients'),
        ),
        migrations.AlterField(
            model_name='generalsliderl',
            name='stuff',
            field=models.SmallIntegerField(verbose_name='Medical Stuff'),
        ),
    ]
