# Generated by Django 5.0 on 2023-12-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_aboutus_alter_generalsliderl_doctors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsliderl',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
