# Generated by Django 5.0 on 2023-12-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_aboutus_title_alter_generalsliderl_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='note1',
            field=models.CharField(max_length=50, verbose_name='First Note'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='note2',
            field=models.CharField(max_length=50, verbose_name='Second Note'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='note3',
            field=models.CharField(max_length=50, verbose_name='Third Note'),
        ),
    ]
