# Generated by Django 5.0 on 2023-12-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_aboutus_note1_alter_aboutus_note2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurDoctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Image')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram URL')),
            ],
            options={
                'verbose_name': 'Our Doctor',
                'verbose_name_plural': 'Our Doctors',
                'ordering': ['name'],
            },
        ),
    ]
