# Generated by Django 5.0 on 2023-12-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_ourdoctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='youtube',
            field=models.URLField(blank=True, verbose_name='Youtube'),
        ),
    ]
