# Generated by Django 4.2.7 on 2023-12-12 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='address',
        ),
        migrations.AddField(
            model_name='header',
            name='aboutstore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abouthead', to='main.aboutstore'),
        ),
    ]
