# Generated by Django 4.2.7 on 2023-12-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_header_address_header_aboutstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('text', models.TextField(max_length=255, verbose_name='Text')),
                ('note1', models.CharField(max_length=20, verbose_name='Note 1')),
                ('note2', models.CharField(max_length=20, verbose_name='Note 2')),
                ('note3', models.CharField(max_length=20, verbose_name='Note 3')),
                ('note4', models.CharField(max_length=20, verbose_name='Note 4')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
    ]
