# Generated by Django 4.2.7 on 2023-12-14 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0023_delete_subpages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date  of the appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appodoc', to='main.ourdoctors'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='message',
            field=models.TextField(max_length=255, null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time of the appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=60, null=True, verbose_name='Name'),
        ),
    ]
