# Generated by Django 4.2.7 on 2023-12-14 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_appointment_options_appointment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('text', models.TextField(max_length=255, verbose_name='Text')),
                ('aboutstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appus', to='main.aboutstore')),
            ],
            options={
                'verbose_name': 'Visit Our Doctor',
                'verbose_name_plural': 'Visit Our Doctor',
            },
        ),
    ]
