# Generated by Django 5.0 on 2023-12-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Page Title',
                'verbose_name_plural': 'Page Titles',
            },
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='title',
        ),
    ]
