# Generated by Django 5.0 on 2023-12-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_pagetitle_remove_testimonial_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='Slide Image')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
