# Generated by Django 5.0.1 on 2024-01-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_newsletter_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourdoctors',
            name='img',
            field=models.ImageField(upload_to='media', verbose_name='Image'),
        ),
    ]
